Enable CRC greentea test
MCU-Driver-HAL/MCU-Driver-ST pull request #10
Opened 2021-07-01 15:38 UTC by gpsimenos

This PR enables the CRC greentea test. The test can be built and run with the existing steps in README.

Accompanies https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/12, to be merged after #12.

2021-07-01 21:02 UTC, MarceloSalazar commented
Looks good.
As https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/12 is merged, we should update the submodule references to the MCU-Driver-HAL repo.
Additionally, please share here the Greentea test logs.

2021-07-05 07:51 UTC, gpsimenos commented
@ithinuel would you be able to paste your greentea logs from the CRC test here?

2021-07-07 11:32 UTC, pfalcon-linaro commented
@MarceloSalazar, @gpsimenos:

> As MCU-Driver-HAL/MCU-Driver-HAL#12 is merged, we should update the submodule references to the MCU-Driver-HAL repo.

I'm trying to figure out how to solve similar issue for my PRs https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/19, https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/13 .

Any suggestions on the "best practices" for that? As far as I can see, initially this PR didn't contain any submodule update at all, then MCU-Driver-HAL's counterpart was merged first, then commit to reference updated MCU-Driver-HAL revision was added here.

The issue is that it doesn't scale to automated CI - there's no (immediate) way how to test PR here until MCU-Driver-HAL's part is merged, but we can't be sure it's correct until it's (at least) built, which requires complete PR in this repo.

Indeed, that looks like the reason why some projects might quit git submodules and devise some adhoc solution which is supposedly easier to use for such cross-repo cases ;-). For example, in zephyr's west manifest it's possible to initially reference "the other PR" as `pull/NNN/head`, have that be built by CI, then when "the other PR" is merged, replace it with the actual commit id/tag. 

But it should be (kinda) possible to do the same with git submodules too, we just need to try, and maybe add some helper scripts/instructions to make that easy.

2021-07-07 11:34 UTC, pfalcon-linaro commented
> I'm trying to figure out ...

Reposted as a separate ticket: https://github.com/MCU-Driver-HAL/MCU-Driver-ST/issues/14

2021-07-07 13:31 UTC, ithinuel requested changes

2021-07-07 13:31 UTC, ithinuel commented on sdfx_st/tests/mbed_hal/crc/CMakeLists.txt
> +set(TEST_TARGET sdfx-st-test-crc)
I find this convoluted.

Why not using those value directly?

2021-07-07 13:31 UTC, ithinuel commented on sdfx_st/tests/mbed_hal/crc/CMakeLists.txt
> +project(${TEST_TARGET})
This like should be 
> Call the project() command near the top of the top-level CMakeLists.txt, but after calling cmake_minimum_required()

according to cmake's [doc](https://cmake.org/cmake/help/latest/command/project.html)

it should be moved around line 17 from this file.

2021-07-12 11:46 UTC, MarceloSalazar commented
@gpsimenos let us know once the PR is ready for review

2021-07-13 07:20 UTC, gpsimenos commented
> @gpsimenos let us know once the PR is ready for review

It's ready for review. Will update MCU-Driver-HAL reference once approved.

2021-07-14 15:38 UTC, ithinuel requested changes

2021-07-14 15:38 UTC, ithinuel commented on sdfx_st/tests/mbed_hal/crc/CMakeLists.txt
> +option(VERBOSE_BUILD "Have a verbose build process")
Can we remove that and what follows please?

2021-07-14 15:56 UTC, MarceloSalazar commented on sdfx_st/tests/mbed_hal/crc/CMakeLists.txt
> +option(VERBOSE_BUILD "Have a verbose build process")
This is needed to be aligned with https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/43

2021-07-15 10:44 UTC, ithinuel submitted a review, later dismissed

2021-07-15 10:59 UTC, gpsimenos commented
MCU-Driver-HAL reference updated, ready for merge

2021-07-15 13:35 UTC, MarceloSalazar approved these changes

2021-07-15 14:59 UTC, merged