Enable uart tests
MCU-Driver-HAL/MCU-Driver-ST pull request #16
Opened 2021-07-13 12:09 UTC by fkjagodzinski

This depends on https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/37 and https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/15, and brings:

- `sdfx_st/tests/mbed_hal_fpga_ci_test_shield/uart`.

2021-07-19 13:44 UTC, hugueskamba reviewed
I suggest you remove the changes that are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19 so your PR is focused on what was needed to enable serial tests. I have marked them with comments.
Thanks.

2021-07-19 13:44 UTC, hugueskamba commented on TARGET_STM32L4/CMakeLists.txt
> -        # gpio_irq_device.c
I do not think this is required given we already have `sdfx_st/hal/src/gpio_irq_device.c`.

2021-07-19 13:44 UTC, hugueskamba commented on sdfx_st/hal/inc/device.h
>  /* mbed Microcontroller Library
A number of changes here are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19. Perhaps you could remove those changes in your branch so the PR is solely focused on the serial test support.

2021-07-19 13:44 UTC, hugueskamba commented on sdfx_st/examples/build_all.sh
> +# Copyright (c) 2021 Arm Limited
A number of changes here are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19. Perhaps you could remove those changes in your branch so the PR is solely focused on the serial test support.

2021-07-19 13:44 UTC, hugueskamba commented on sdfx_st/examples/clean_all.sh
> +# Copyright (c) 2021 Arm Limited
A number of changes here are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19. Perhaps you could remove those changes in your branch so the PR is solely focused on the serial test support.

2021-07-19 13:44 UTC, hugueskamba commented on sdfx_st/hal/inc/PeripheralPins.h
>  #include "pinmap.h"
A number of changes here are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19. Perhaps you could remove those changes in your branch so the PR is solely focused on the serial test support.

2021-07-19 13:44 UTC, hugueskamba commented on sdfx_st/hal/inc/rtc_api_hal.h
> +// Possible choices of the RTC_CLOCK_SOURCE configuration set in json file
A number of changes here are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19. Perhaps you could remove those changes in your branch so the PR is solely focused on the serial test support.

2021-07-19 13:44 UTC, hugueskamba commented on sdfx_st/tests/mbed_hal/crc/CMakeLists.txt
> +project(sdfx-st-test-crc)
A number of changes here are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19. Perhaps you could remove those changes in your branch so the PR is solely focused on the serial test support.

2021-07-19 13:44 UTC, hugueskamba commented on sdfx_st/tests/mbed_hal/echo/CMakeLists.txt
> +add_executable(sdfx-st-test-echo)
A number of changes here are included in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19. Perhaps you could remove those changes in your branch so the PR is solely focused on the serial test support.

2021-07-19 13:57 UTC, fkjagodzinski commented
@hugueskamba thanks for the review. This PR is still a draft; a couple of things have to be merged to unblock this:

- https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/37
- https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/15
- https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/19

When these are done, I'll rebase and leave only the commits that relevant for enabling Serial test-shield tests (i.e. **only the last 3 commits**).

2021-07-19 15:17 UTC, hugueskamba commented on sdfx_st/tests/mbed_hal_fpga_ci_test_shield/uart/CMakeLists.txt
> +endif()
```suggestion
```

2021-07-22 14:53 UTC, MarceloSalazar commented
@fkjagodzinski dependencies merged - you can proceed to rebase/clean-up :)

2021-07-23 07:34 UTC, fkjagodzinski commented
OK, the commit history has been cleaned up; only the relevant changes are left. This is ready; @hugueskamba , @MarceloSalazar , please review.

2021-07-23 07:40 UTC, fkjagodzinski commented
`./build_all.sh` executed in `MCU-Driver-ST/sdfx_st/tests`:

```
BUILD SUMMARY:
./mbed_hal/us_ticker
./mbed_hal/us_ticker_lp_ticker_frequency
./mbed_hal/us_ticker_lp_ticker_common
./mbed_hal/echo
./mbed_hal/crc
./mbed_hal/trng
./mbed_hal_fpga_ci_test_shield/gpio_irq
./mbed_hal_fpga_ci_test_shield/gpio
./mbed_hal_fpga_ci_test_shield/uart
```

`./run_all.sh` executed in `MCU-Driver-ST/sdfx_st/tests`:

```
RUN SUMMARY:
./mbed_hal/us_ticker/cmake_build/sdfx-st-test-us_ticker.bin
./mbed_hal/us_ticker_lp_ticker_frequency/cmake_build/sdfx-st-test-us_ticker_lp_ticker_frequency.bin
./mbed_hal/us_ticker_lp_ticker_common/cmake_build/sdfx-st-test-us_ticker_lp_ticker_common.bin
./mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin
./mbed_hal/crc/cmake_build/sdfx-st-test-crc.bin
./mbed_hal/trng/cmake_build/sdfx-st-test-trng.bin
./mbed_hal_fpga_ci_test_shield/gpio_irq/cmake_build/sdfx-st-fpga_ci_test_shield-gpio_irq.bin
./mbed_hal_fpga_ci_test_shield/gpio/cmake_build/sdfx-st-fpga_ci_test_shield-gpio.bin
./mbed_hal_fpga_ci_test_shield/uart/cmake_build/sdfx-st-fpga_ci_test_shield-uart.bin
```


<details>
<summary>Detailed output from `mbed_hal_fpga_ci_test_shield/uart` added in this PR.</summary>

```
Running ./mbed_hal_fpga_ci_test_shield/uart/cmake_build/sdfx-st-fpga_ci_test_shield-uart.bin
[1627025494.81][HTST][INF] host test executor ver. 0.0.15
[1627025494.81][HTST][INF] copy image onto target...
[1627025500.74][MBED][WRN] Target ID not found: Skipping flash check and retry
[1627025500.74][HTST][INF] starting host test process...
[1627025500.75][CONN][INF] starting connection process...
[1627025500.75][CONN][INF] notify event queue about extra 60 sec timeout for serial port pooling
[1627025500.75][CONN][INF] initializing serial port listener... 
[1627025500.75][SERI][INF] serial(port=/dev/ttyACM0, baudrate=115200, read_timeout=0.01, write_timeout=5)
[1627025500.75][HTST][INF] setting timeout to: 60 sec
[1627025500.75][SERI][INF] reset device using 'default' plugin...
[1627025500.85][SERI][INF] waiting 1.00 sec after reset
[1627025501.85][SERI][INF] wait for it...
[1627025501.86][SERI][TXD] mbedmbedmbedmbedmbedmbedmbedmbedmbedmbed
[1627025501.86][CONN][INF] sending up to 2 __sync packets (specified with --sync=2)
[1627025501.86][CONN][INF] sending preamble 'a5e08fbd-7cb6-406e-9217-13a66deccdd4'
[1627025501.86][SERI][TXD] {{__sync;a5e08fbd-7cb6-406e-9217-13a66deccdd4}}
[1627025501.87][CONN][RXD] mbedmbedmbedmbedmbedmbedmbedmbed
[1627025501.87][CONN][INF] found SYNC in stream: {{__sync;a5e08fbd-7cb6-406e-9217-13a66deccdd4}} it is #0 sent, queued...
[1627025501.87][HTST][INF] sync KV found, uuid=a5e08fbd-7cb6-406e-9217-13a66deccdd4, timestamp=1627025501.873270
[1627025501.88][CONN][RXD] >>> Running 24 test cases...
[1627025501.88][CONN][INF] found KV pair in stream: {{__version;1.3.0}}, queued...
[1627025501.88][CONN][INF] found KV pair in stream: {{__timeout;240}}, queued...
[1627025501.88][CONN][INF] found KV pair in stream: {{__host_test_name;default_auto}}, queued...
[1627025501.88][CONN][INF] found KV pair in stream: {{__testcase_count;24}}, queued...
[1627025501.89][HTST][INF] DUT greentea-client version: 1.3.0
[1627025501.89][HTST][INF] setting timeout to: 240 sec
[1627025501.89][HTST][INF] host test class: '<class 'mbed_os_tools.test.host_tests.default_auto.DefaultAuto'>'
[1627025501.89][HTST][INF] host test setup() call...
[1627025501.89][HTST][INF] CALLBACKs updated
[1627025501.89][HTST][INF] host test detected: default_auto
[1627025501.90][CONN][INF] found KV pair in stream: {{__testcase_name;init/free, FC off}}, queued...
[1627025501.90][CONN][INF] found KV pair in stream: {{__testcase_name;basic, 9600, 8N1, FC off}}, queued...
[1627025501.91][CONN][INF] found KV pair in stream: {{__testcase_name;basic (direct init), 9600, 8N1, FC off}}, queued...
[1627025501.91][CONN][INF] found KV pair in stream: {{__testcase_name;basic, 9600, 7N1, FC off}}, queued...
[1627025501.91][CONN][INF] found KV pair in stream: {{__testcase_name;basic, 9600, 9N1, FC off}}, queued...
[1627025501.92][CONN][INF] found KV pair in stream: {{__testcase_name;19200, 8N1, FC off}}, queued...
[1627025501.92][CONN][INF] found KV pair in stream: {{__testcase_name;38400, 8N1, FC off}}, queued...
[1627025501.92][CONN][INF] found KV pair in stream: {{__testcase_name;115200, 8N1, FC off}}, queued...
[1627025501.93][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 8N2, FC off}}, queued...
[1627025501.93][CONN][INF] found KV pair in stream: {{__testcase_name;init/free, FC on}}, queued...
[1627025501.93][CONN][INF] found KV pair in stream: {{__testcase_name;basic, 9600, 8N1, FC on}}, queued...
[1627025501.94][CONN][INF] found KV pair in stream: {{__testcase_name;basic (direct init), 9600, 8N1, FC on}}, queued...
[1627025501.94][CONN][INF] found KV pair in stream: {{__testcase_name;basic, 9600, 7N1, FC on}}, queued...
[1627025501.95][CONN][INF] found KV pair in stream: {{__testcase_name;basic, 9600, 9N1, FC on}}, queued...
[1627025501.95][CONN][INF] found KV pair in stream: {{__testcase_name;19200, 8N1, FC on}}, queued...
[1627025501.95][CONN][INF] found KV pair in stream: {{__testcase_name;38400, 8N1, FC on}}, queued...
[1627025501.95][CONN][INF] found KV pair in stream: {{__testcase_name;115200, 8N1, FC on}}, queued...
[1627025501.96][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 8O1, FC on}}, queued...
[1627025501.96][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 7O1, FC on}}, queued...
[1627025501.96][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 9O1, FC on}}, queued...
[1627025501.97][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 8E1, FC on}}, queued...
[1627025501.97][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 7E1, FC on}}, queued...
[1627025501.97][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 9E1, FC on}}, queued...
[1627025501.98][CONN][RXD] 
[1627025501.98][CONN][RXD] >>> Running case #1: 'init/free, FC off'...
[1627025501.98][CONN][INF] found KV pair in stream: {{__testcase_name;9600, 8N2, FC on}}, queued...
[1627025501.98][CONN][INF] found KV pair in stream: {{__testcase_start;init/free, FC off}}, queued...
[1627025501.99][CONN][RXD] ***Testing UART-no-FC on all form factor ports***
[1627025501.99][CONN][RXD] D0 - RX pin tested on port: peripheral=(0x40004c00) TX=(D1) RX=(D0) ...succeeded
[1627025502.00][CONN][RXD] D1 - TX pin tested on port: peripheral=(0x40004c00) TX=(D1) RX=(D0) ...test already done...succeeded
[1627025502.01][CONN][RXD] D2 - Could not find pins to test TX pin D2 (62)
[1627025502.01][CONN][RXD] D3 - Could not find pins to test TX pin D3 (16)
[1627025502.02][CONN][RXD] D4 - RX pin tested on port: peripheral=(0x40004400) TX=(D10) RX=(D4) ...succeeded
[1627025502.02][CONN][RXD] D5 - Could not find pins to test TX pin D5 (20)
[1627025502.02][CONN][RXD] D6 - Could not find pins to test TX pin D6 (17)
[1627025502.04][CONN][RXD] D7 - Could not find pins to test TX pin D7 (4)
[1627025502.04][CONN][RXD] D8 - Could not find pins to test TX pin D8 (18)
[1627025502.04][CONN][RXD] D9 - Could not find pins to test TX pin D9 (15)
[1627025502.05][CONN][RXD] D10 - TX pin tested on port: peripheral=(0x40004400) TX=(D10) RX=(D4) ...test already done...succeeded
[1627025502.06][CONN][RXD] D11 - Could not find pins to test TX pin D11 (7)
[1627025502.06][CONN][RXD] D12 - Could not find pins to test TX pin D12 (6)
[1627025502.06][CONN][RXD] D13 - Could not find pins to test TX pin D13 (5)
[1627025502.07][CONN][RXD] D14 - Could not find pins to test TX pin D14 (25)
[1627025502.07][CONN][RXD] D15 - Could not find pins to test TX pin D15 (24)
[1627025502.08][CONN][RXD] A0 - RX pin tested on port: peripheral=(0x40004800) TX=(A1) RX=(A0) ...succeeded
[1627025502.09][CONN][RXD] A1 - TX pin tested on port: peripheral=(0x40004800) TX=(A1) RX=(A0) ...test already done...succeeded
[1627025502.09][CONN][RXD] A2 - Could not find pins to test TX pin A2 (35)
[1627025502.09][CONN][RXD] A3 - Could not find pin [...]

2021-07-23 08:24 UTC, MarceloSalazar submitted a review, later dismissed

2021-07-23 11:06 UTC, hugueskamba requested changes

2021-07-23 11:06 UTC, hugueskamba commented on sdfx_st/.mbedbuild/mbed_config_gcc.cmake
> +    "UART_9BITS_PARITY_NOT_SUPPORTED"
Please add this to the test CMakeLists.txt (`sdfx_st/tests/mbed_hal_fpga_ci_test_shield/uart/CMakeLists.txt`).
This macro is specific to the test.

```cmake
target_compile_definitions(sdfx-st-fpga_ci_test_shield-uart
    PUBLIC
        UART_9BITS_PARITY_NOT_SUPPORTED
)
```

2021-07-23 11:09 UTC, ithinuel commented on sdfx_st/.mbedbuild/mbed_config_gcc.cmake
> +    "UART_9BITS_PARITY_NOT_SUPPORTED"
for reference it lives [TESTS/configs/fpga.json](https://github.com/ARMmbed/mbed-os/blob/master/TESTS/configs/fpga.json) in mbed-os

2021-07-23 11:44 UTC, fkjagodzinski commented on sdfx_st/.mbedbuild/mbed_config_gcc.cmake
> +    "UART_9BITS_PARITY_NOT_SUPPORTED"
Done. That is now part of single commit this PR introduces.

The suggested solution did not work for me; had to change that to `target_compile_definitions(sdfx-fpga_ci_test_shield-uart ...)` (the CMake target provided by the HAL repo).

2021-07-23 12:28 UTC, hugueskamba approved these changes

2021-07-23 12:30 UTC, ithinuel approved these changes

2021-07-23 13:12 UTC, MarceloSalazar approved these changes

2021-07-23 13:12 UTC, merged