Fix various issues with the projects
MCU-Driver-HAL/MCU-Driver-ST pull request #19
Opened 2021-07-16 17:09 UTC by hugueskamba

See individual commits for details:
* Fix examples and test build errors
* Fix examples clean and build scripts
* Fix CRC Greentea test (requires https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/48 as well as commits in this PR)
* Cleanup echo Greentea test
* Ignore VSCode files

DEPENDS ON https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/48

2021-07-19 08:14 UTC, fkjagodzinski requested changes

2021-07-19 08:14 UTC, fkjagodzinski commented on sdfx_st/hal/inc/device.h
> + #define DEVICE_ID_LENGTH       24
```suggestion
#define DEVICE_ID_LENGTH       24
```

This applies to every new line in this file.

2021-07-19 08:46 UTC, hugueskamba commented on sdfx_st/hal/inc/device.h
> + #define DEVICE_ID_LENGTH       24
[Done](https://github.com/MCU-Driver-HAL/MCU-Driver-ST/compare/5ae9d7b92278fb06f5f22dfb7733b3e2e030c95a..05ba2dd1d32f7ba9dc49a2d03068861f30908cea).

2021-07-19 09:13 UTC, fkjagodzinski approved these changes

2021-07-21 13:51 UTC, hugueskamba commented
This [force-push](https://github.com/MCU-Driver-HAL/MCU-Driver-ST/compare/05ba2dd1d32f7ba9dc49a2d03068861f30908cea..47e38b1cf3306bc6952af4612cd042fac6110bfa) updates the reference to MCU-Driver-HAL after https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/48 was merged.

2021-07-21 21:30 UTC, fkjagodzinski approved these changes

2021-07-22 09:16 UTC, MarceloSalazar approved these changes

2021-07-22 09:20 UTC, ithinuel approved these changes

2021-07-22 09:20 UTC, merged