Added a -GNinja flag to the build file generation step
MCU-Driver-HAL/MCU-Driver-ST pull request #8
Opened 2021-06-29 16:09 UTC by Jambls

Ideally located in the test build instructions, the build file generation step for running the tests doesn't include the -GNinja flag, while the same instruction for running an example program does.
Without this, it was causing issues with building on windows as Cmake would try and find Nmake (part of visual studio) which is not guaranteed to be present on a windows system, while Ninja should be present on a system that has been set up with all the mbed tools and dependencies.

2021-06-29 17:04 UTC, MarceloSalazar submitted a review, later dismissed

2021-06-30 09:22 UTC, fkjagodzinski approved these changes
LGTM

2021-06-30 09:35 UTC, fkjagodzinski requested changes
Actually, I just noticed we may want to update the comment below the command. It mentions the `-G` flag.

2021-06-30 10:51 UTC, fkjagodzinski approved these changes

2021-06-30 13:12 UTC, MarceloSalazar approved these changes

2021-06-30 13:12 UTC, merged